[package]
name = "ccc-types"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
ts-rs = {version = "8.0.0" }
