[package]
name = "ccc-types"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
ts-rs = {version = "6.2.1" }
