[package]
name = "ccc-types"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
ts-rs = {version = "7.0.0" }
