[package]
name = "ccc-types"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.176", features = ["derive"] }
serde_json = "1.0.102"
ts-rs = { git = 'https://github.com/frog-pond/ts-rs.git', tag = '6.2.2' }
