[package]
name = "ccc-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.1"
types = { path = "../types" }
routes = { path = "../routes" }
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.139", features = ["derive"] }
tokio = { version = "1.23.1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["filter", "timeout"] }
tower-http = { version = "0.3.5", features = ["trace"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
