[package]
name = "ccc-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.6.20", features = ["headers", "tracing"] }
clap = { version = "4.4.6", features = ["derive"] }
ccc-types = { path = "../ccc-types" }
ccc-routes = { path = "../ccc-routes" }
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.192", features = ["derive"] }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["filter", "timeout"] }
tower-http = { version = "0.4.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
