[package]
name = "ccc_server_next"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
axum = "0.4.5"
types = { path = "./types" }
routes = { path = "./routes" }
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4", features = ["filter"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[workspace]
members = [
    "handlers",
    "routes",
    "types",
]
