[package]
name = "ccc_server_next"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
axum = "0.5.13"
types = { path = "./types" }
routes = { path = "./routes" }
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.139", features = ["derive"] }
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["filter"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.14"

[workspace]
members = [
	"handlers",
	"routes",
	"types",
]
