[package]
name = "ccc-server-next"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.4.5"
reqwest = { version = "0.11.9", features = ["json"] }
serde_json = "1.0.78"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
