// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BonAppSingleCafeResponse } from "./BonAppSingleCafeResponse";

export type BonAppCafesResponse = { cafes: Record<string, BonAppSingleCafeResponse>, };