[package]
name = "ccc-server-routes"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
ccc-upstream-handlers = { workspace = true }
