[package]
name = "handlers"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
axum = "0.4.5"
types = { path = "../types" }
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
thiserror = { version = "1.0.30" }
