[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.17"
url = "2.3.1"
bytes = "1.4.0"
similar = "2.2.1"
serde_json = "1.0.93"
