[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.23"
url = "2.5.0"
bytes = "1.5.0"
similar = "2.4.0"
serde_json = "1.0.108"
