[package]
name = "e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11.22"
url = "2.5.0"
bytes = "1.5.0"
similar = "2.3.0"
serde_json = "1.0.108"
