[package]
name = "ccc-proxy"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.3"
bytes = "1.5.0"
http = "1.0.0"
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.114"
thiserror = { version = "1.0.53" }
tracing = "0.1.40"
