[package]
name = "ccc-handlers"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.20"
axum-macros = "0.3.8"
http = "0.2.9"
ccc-types = { path = "../ccc-types" }
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
thiserror = { version = "1.0.47" }
tracing = "0.1.37"
serde_urlencoded = "0.7.1"
phf = { version = "0.11.2", features = ["macros"] }
