[package]
name = "ccc-handlers"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ccc-proxy = { path = "../ccc-proxy" }
ccc-types = { path = "../ccc-types" }
axum = "0.6.20"
axum-macros = "0.3.8"
http = "0.2.9"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
thiserror = { version = "1.0.50" }
tracing = "0.1.37"
serde_urlencoded = "0.7.1"
phf = { version = "0.11.2", features = ["macros"] }
