/* tslint:disable */

/* WARNING: This file is automatically generated */
/* DO NOT CHANGE IT MANUALLY */

export interface BreakSchedule {
  fall: Array<Schedule>;
  thanksgiving: Array<Schedule>;
  winter: Array<Schedule>;
  interim: Array<Schedule>;
  spring: Array<Schedule>;
  easter: Array<Schedule>;
  summer: Array<Schedule>;
}

export interface BusTimesResponse {
  data: Array<BusTimesResponseItem>;
}

export interface BusTimesResponseItem {
  colors: TransitColors;
  line: string;
  notice: string | null;
  schedules: Array<TransitSchedule>;
}

export interface ColorPrintersResponse {
  data: ColorPrintersResponseItem;
}

export interface ColorPrintersResponseItem {
  colorPrinters: Array<string>;
}

export interface ContactResponse {
  data: Array<ContactResponseItem>;
}

export interface ContactResponseItem {
  title: string;
  phoneNumber: string | null;
  buttonText: string | null;
  category: string;
  image?: string;
  synopsis: string;
  text: string;
}

export type DayOfWeek = "Mo" | "Tu" | "We" | "Th" | "Fr" | "Sa" | "Su";

export interface DictionaryResponse {
  data: Array<DictionaryResponseItem>;
}

export interface DictionaryResponseItem {
  word: string;
  definition: string;
}

export interface FAQResponse {
  text: string;
}

export interface FoodItemResponse {
  label: string;
  station: string;
  description?: string;
  special?: boolean;
}

export interface FoodStationMenu {
  label: string;
  note?: string;
}

export interface HelpButton {
  title: string;
  action: string;
  params: HelpParams;
}

export interface HelpParams {
  url?: string;
  number?: string;
  to?: string;
  subject?: string;
  body?: string;
}

export interface HelpResponse {
  data: Array<HelpResponseItem>;
}

export interface HelpResponseItem {
  key: string;
  enabled: boolean;
  hidden: boolean;
  title: string;
  body: string;
  buttons: Array<HelpButton>;
}

export interface Hour {
  days: Array<DayOfWeek>;
  from: string;
  to: string;
}

export interface HoursItem {
  name: string;
  image?: string;
  category: string;
  schedule: Array<BreakSchedule>;
  breakSchedule: BreakSchedule;
  subtitle?: string;
}

export interface HoursResponse {
  data: Array<HoursItem>;
}

export interface ModesItem {
  name: string;
  category: string;
  description: string;
  synopsis: string;
  url: string;
}

export interface ModesResponse {
  data: Array<ModesItem>;
}

export interface PauseMenuItemResponse {
  stationMenus: Array<FoodStationMenu>;
  foodItems: Array<FoodItemResponse>;
  corIcons: Array<any>;
}

export interface PauseMenuResponse {
  data: PauseMenuItemResponse;
}

export interface Schedule {
  title: string;
  notes?: string;
  hours: Array<Hour>;
  closedForChapelTime: boolean | null;
  isPhysicallyOpen: boolean | null;
}

export interface TransitColors {
  bar: string;
  dot: string;
}

export interface TransitSchedule {
  days: Array<string>;
  coordinates: Record<string, Array<number>>;
  stops: Array<string>;
  times: Array<Array<string | boolean>>;
}

export interface WebcamsResponse {
  data: Array<WebcamsResponseItem>;
}

export interface WebcamsResponseItem {
  name: string;
  pageUrl: string;
  streamUrl: string;
  thumbnail: string;
  thumbnailUrl?: string;
  tagline: string;
  accentColor: Array<bigint>;
  textColor: string;
}
