name: Build and Test

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  check:
    name: Check the code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    steps:
      - name: Install the appropriate Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - name: Run rustfmt
        run: |
          rustup component add rustfmt
          mise run fmt-check
      - name: Run clippy
        run: |
          rustup component add clippy
          mise run clippy

  test:
    name: Test the code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    steps:
      - name: Install the appropriate Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - name: Run cargo test
        run: |
          mise run test
      - name: Ensure index.d.ts is up-to-date after tests were run
        run: |
          mise run diff
