name: Build and Test

on:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  check:
    name: Check the code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    steps:
      - name: Install the appropriate Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4
      - name: Run rustfmt
        run: |
          rustup component add rustfmt
          mise run fmt-check
      - name: Run clippy
        run: |
          rustup component add clippy
          mise run clippy

  test:
    name: Test the code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    steps:
      - name: Install the appropriate Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4
      - name: Run cargo test
        run: |
          mise run test
      - name: Ensure index.d.ts is up-to-date after tests were run
        run: |
          mise run diff
